# Name : Shrook Ehab Attia
# Group 1 - AI - Nasr City
# PSFML Homework 3&4&5

### 1. Your data table rows represent 1000 different clients picked at random and are independent

In [23]:
sample = 1000 # number of random variables

### 3. The marital status (M) is either Married (1) or Others (0). “Others” may represent singles, widows and divorced. Construct 1000 samples with probability of being married = 0.6 [Hint: n=1]

##### using scipy

In [24]:
from scipy.stats import binom

M = binom.rvs(n=1,p=0.6,size=1000)
print(M[0:20])

[1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 1]


##### using numpy

In [25]:
import numpy as np

n = 1
p = 0.6
sample = 1000
M = np.random.binomial(n, p, sample) 
print(M[0:20])

[1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1]


### 4. The No. of dependents (ND) like children, spouse, parents, in-laws, etc. whom the client might need to finance yearly over the duration of the loan. Construct 1000 samples with average ND is 2. [Hint: lambda=2]

##### using scipy

In [26]:
from scipy.stats import poisson

ND = poisson.rvs(mu=2, size=1000)
print(ND[0:20])

[2 1 2 5 3 1 3 3 2 3 7 4 5 3 1 1 6 1 3 2]


##### using numpy

In [27]:
mu = 2 #average rate "λ"
ND = np.random.poisson(mu, sample) 
print(ND[0:20])

[4 1 0 1 0 2 1 1 3 2 1 3 0 1 3 1 3 1 2 3]


### 5. The client’s annual income in order of 1k (AI) is supposed to be obeying a normal distribution N(80,400). Construct 1000 samples.

##### using scipy

In [28]:
from scipy.stats import norm

# generate random numbers from N(80,400)
AI = norm.rvs(size=sample,loc=80,scale=400)
print(AI[0:20])

[-521.71969057  729.46966081  180.65473367  272.7264862  -378.03794851
 -171.86158803  -10.34611673  104.99970544  -38.28056744  -71.71826641
  -96.87538525  320.07830136   75.36316088  197.46475342  595.40591813
 -158.45722727   62.60183311 -818.30983765 -690.19513645 -547.06021977]


##### using numpy

In [29]:
# generate random numbers from N(80,400)
mean = 80
std = 400
AI = np.random.normal(mean, std, sample) 
print(AI[0:20])

[  41.21504503  510.7603335   510.83707721   73.28397162  -92.08120928
 -361.54577994   11.8079849    -2.81747823 -108.24269168 -216.96894544
  185.30980206  560.18546487  480.09504756 -207.7652817  -206.33977301
  119.24121701  232.38069536 -390.06168125 -587.95955176  153.29355488]


### 6. The risk associated to No-cashback (R), is either high (>0.5) or low (<=0.5) and is computed using the following formula: R = 12 * ( ND + 1 ) / AI => Construct 1000 samples.

In [30]:
R = 12 * ( ND + 1 ) / AI
print(R[0:20])
len(R)

[ 1.45577907  0.04698877  0.02349086  0.32749317 -0.13031975 -0.09957245
  2.03252293 -8.51825569 -0.44344795 -0.16592236  0.12951285  0.08568591
  0.02499505 -0.11551497 -0.23262602  0.20127269  0.20655761 -0.06152873
 -0.0612287   0.31312471]


1000

### 7. The past experience whether or not the client has had a previous approved loan (HA) is either Yes (=1) or No (=0). Construct a 1000 samples with probability of being cashed a loan = 0.3 [Hint: n=1]

##### using scipy

In [31]:
HA = binom.rvs(n=1,p=0.3,size=sample)
print(HA[0:20])

[1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0]


##### using numpy

In [32]:
n = 1
p = 0.3
HA = np.random.binomial(n, p, sample) 
print(HA[0:20])

[0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0]


### 8. The amount of previously approved loan (AA) is supposed to be a function of a normal distribution N(100,100). : AA = HA * ( 0.1 * AI + R * N(100,100) ) In other words, if he was cashed a previous loan (HA = 1) he got a legal amount of 10% of his annual income in addition to a percentage of 100k with tolerance, conditioned with his risk factor. Construct 1000 samples.

##### using scipy

In [33]:
# generate random numbers from N(100,100)
NN = norm.rvs(size=sample,loc=100,scale=100)
AA = HA * ( 0.1 * AI + R * NN)
print(AA[0:20])

[    0.             0.             0.             0.
    -0.            -0.             0.         -1640.79530418
    -0.           -37.74570868    32.98948279    66.59325802
    51.43048635    -0.            -0.            -0.
     0.            -0.            -0.             0.        ]


##### using numpy

In [34]:
# generate random numbers from N(100,100)
mean = 100
std = 100
NN = np.random.normal(mean, std, sample) 
AA = HA * ( 0.1 * AI + R * NN)
print(AA[0:20])

[   0.            0.            0.            0.           -0.
   -0.            0.         -844.05846262   -0.          -38.8646776
   16.69984838   74.8171676    53.14208444   -0.           -0.
    0.            0.           -0.           -0.            0.        ]


### 9. The time until he was granted the approval of his previous loan (TA) is exponentially distributed with decay/scale parameter lambda = 2 : TA = HA* Exp(lambda) . Construct 1000 samples.

##### using scipy

In [35]:
from scipy.stats import expon
exp = expon.rvs(scale=2,loc=0,size=1000)
TA = HA * exp
print(TA[0:20])

[0.         0.         0.         0.         0.         0.
 0.         3.69681801 0.         6.41028228 2.51300358 0.58043281
 2.29511779 0.         0.         0.         0.         0.
 0.         0.        ]


##### using numpy

In [36]:
scale = 2
exp = np.random.exponential(scale, sample)
TA = HA * exp
print(TA[0:20])

[0.         0.         0.         0.         0.         0.
 0.         1.44666133 0.         1.00403567 0.87309591 2.39613494
 3.56807626 0.         0.         0.         0.         0.
 0.         0.        ]


### 10. The year of last approved loan (YA) is uniformly distributed between 2000-2020. YA = HA* {U(2000,2020)} Construct 1000 samples. [Hint: use x.astype(int) to convert float value to integers]

##### using scipy

In [37]:
from scipy.stats import uniform
# generate/create random numbers (rvs) from uniform distribution between 2000-2020
start = 2000  
width = 2020 - 2000 
UN = uniform.rvs(size=sample, loc = start, scale=width)
YA = HA * UN 
YA = YA.astype(int) 
print(YA[0:20])

[   0    0    0    0    0    0    0 2014    0 2000 2004 2015 2004    0
    0    0    0    0    0    0]


##### using numpy

In [38]:
# generate/create random numbers (rvs) from uniform distribution between 2000-2020
start = 2000  
width = 2020 - 2000 
UN = np.random.uniform(start, width, sample)
YA = HA * UN 
YA = YA.astype(int) 
print(YA[0:20])

[   0    0    0    0    0    0    0  596    0 1106 1375 1497 1640    0
    0    0    0    0    0    0]


### 2. Each data sample (i.e. table row) has some attributes with random values (continuous and discrete), namely: 
#### M = Marital status
#### ND = No. of dependents
#### AI = Client’s annual income
#### R = Risk associated to No-cashback
#### HA = Has previous approved loan
#### AA = Amount of previously approved loan
#### TA = Time until loan is approved
#### YA = Year of last approved loan

In [39]:
import pandas as pd

cols = {'Marital status(M)':M, 'No. of dependents(ND)':ND, 'Annual income(AI)':AI, 'Risk(R)':R, 'Has prev.approved loan(HA)':HA, 'Amount of prev.approved loan(AA)':AA, 'Time until loan is approved(TA)':TA, 'Year of last approved loan(YA)':YA}
data = pd.DataFrame(cols)
data.head()

Marital status(M)  No. of dependents(ND)  Annual income(AI)   Risk(R)  \
0                  1                      4          41.215045  1.455779   
1                  1                      1         510.760334  0.046989   
2                  1                      0         510.837077  0.023491   
3                  1                      1          73.283972  0.327493   
4                  0                      0         -92.081209 -0.130320   

   Has prev.approved loan(HA)  Amount of prev.approved loan(AA)  \
0                           0                               0.0   
1                           0                               0.0   
2                           0                               0.0   
3                           0                               0.0   
4                           0                              -0.0   

   Time until loan is approved(TA)  Year of last approved loan(YA)  
0                              0.0                               0  
1                              0.0                               0  
2                              0.0                               0  
3                              0.0                               0  
4                              0.0                               0

### Using the table columns (Arrays) you created compute the following:
#### a. Probability to get a loan application by an unmarried client with 2 parent dependents

In [40]:
trueRows = data[(data['Marital status(M)'] == 0) & (data['No. of dependents(ND)'] == 2)]
print("probability is: ", len(trueRows)/sample)

probability is:  0.12


#### b. Probability that a loan application will take more than 5 months to get approved

In [41]:
trueRows = data[data['Time until loan is approved(TA)'] > 5]
print("probability is: ", len(trueRows)/sample)

probability is:  0.025


#### c. Probability that a loan less than 100k will be approved to a client given that he has been cashed a previous loan?

In [42]:
probLoan = len(data['Has prev.approved loan(HA)']) / sample
trueRows = len(data[(data['Amount of prev.approved loan(AA)'] < 100) & (data['Has prev.approved loan(HA)'] == 1)]) /sample
print("probability is: ", trueRows / probLoan)

probability is:  0.274


#### d. Describe the correlation between the no. of dependents (ND) and the risk factor (R)

In [47]:
correlation = data['No. of dependents(ND)'].corr(data['Risk(R)'])
print("correlation between ND and R is: ", correlation)
print("This correlation is weak as it is < 0.3 which means they are nearly independent or have no linear relation")

correlation between ND and R is:  -0.00028280730926121537
This correlation is weak as it is < 0.3 which means they are nearly independent or have no linear relation


#### e. Describe the correlation between the annual income (AI) and the risk factor (R)

In [48]:
correlation = data['Annual income(AI)'].corr(data['Risk(R)'])
print("correlation is: ", correlation)
print("This correlation is weak as it is < 0.3 which means they are nearly independent or have no linear relation")

correlation is:  0.01030841160501198
This correlation is weak as it is < 0.3 which means they are nearly independent or have no linear relation
